import esbuild from "esbuild";
import process from "process";
import { readFileSync, writeFileSync } from "fs";
import path from "path";

const builtins = [
	"assert", "async_hooks", "buffer", "child_process", "cluster", "console",
	"constants", "crypto", "dgram", "dns", "domain", "events", "fs", "http",
	"http2", "https", "inspector", "module", "net", "os", "path", "perf_hooks",
	"process", "punycode", "querystring", "readline", "repl", "stream",
	"string_decoder", "timers", "tls", "trace_events", "tty", "url", "util",
	"v8", "vm", "worker_threads", "zlib",
];

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Tree-shaking note: every export in this codebase is genuinely reachable — all
// species definitions feed into STARDEW_SPECIES_OPTIONS and the speciesById map,
// and every sprite import is referenced by at least one species or NPC definition.
// esbuild's treeShaking is working correctly; there simply isn't dead code *to* remove.
//
// To audit the bundle, pass --metafile (generates meta.json):
//   node esbuild.config.mjs production --metafile
// Then visualize with:
//   npx esbuild-visualizer --metadata meta.json --filename viz.html

const metafile = prod && process.argv.includes("--metafile");

// Plugin to bundle images as base64 data URLs
const imagePlugin = {
	name: 'images',
	setup(build) {
		build.onResolve({ filter: /\.(png|jpg|jpeg|gif|svg)$/ }, args => {
			return {
				path: path.resolve(args.resolveDir, args.path),
				namespace: 'image'
			};
		});

		build.onLoad({ filter: /.*/, namespace: 'image' }, args => {
			const imageBuffer = readFileSync(args.path);
			const base64 = imageBuffer.toString('base64');
			const ext = path.extname(args.path).slice(1);
			const mimeType = {
				'png': 'image/png',
				'jpg': 'image/jpeg',
				'jpeg': 'image/jpeg',
				'gif': 'image/gif',
				'svg': 'image/svg+xml'
			}[ext] || 'application/octet-stream';

			return {
				contents: `export default "data:${mimeType};base64,${base64}"`,
				loader: 'js'
			};
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	metafile,
	plugins: [imagePlugin],
});

if (prod) {
	const result = await context.rebuild();
	if (metafile) {
		writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
		console.log("Wrote meta.json for bundle analysis.");
	}
	process.exit(0);
} else {
	await context.watch();
}
